# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bad_ass_extensions"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jason Amster"]
  s.date = "2012-06-07"
  s.description = "Some bad ass extensions I use all the time"
  s.email = "jayamster@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.mdown"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.mdown",
    "Rakefile",
    "VERSION",
    "bad_ass_extensions.gemspec",
    "lib/bad_ass_extensions.rb",
    "lib/bad_ass_extensions/array.rb",
    "lib/bad_ass_extensions/cookie_debugger.rb",
    "lib/bad_ass_extensions/date.rb",
    "lib/bad_ass_extensions/enumerable.rb",
    "lib/bad_ass_extensions/hash.rb",
    "lib/bad_ass_extensions/histogram.rb",
    "lib/bad_ass_extensions/object.rb",
    "test/helper.rb",
    "test/test_bad_ass_extensions.rb"
  ]
  s.homepage = "http://github.com/jamster/bad_ass_extensions"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.21"
  s.summary = "Some bad ass extensions I use all the time"
  s.test_files = [
    "test/helper.rb",
    "test/test_bad_ass_extensions.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

